services:
  mysql:
    image: mariadb:11.1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
  nginx:
    image: nginx:1.26.0-alpine
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
  app:
    image: tialy
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
volumes:
  mysql:
